GET http://localhost:8080/modelRest/detail/4
Accept: application/json

###
POST http://localhost:8080/modelRest/create
Content-Type: application/json

{
  "modelName": "mcznxcznx",
  "modelEmail": "bichphuong95@gmail.com",
  "modelBirthDay": "2020-10-15",
  "modelHobby": null,
  "urlImg": "bich_phuong.jpg",
  "city": null
}

###
GET http://localhost:8080/modelRest/list
Accept: application/json

###
